pimpbeam {
  secret = "changeme"
  secret = ${?APPLICATION_SECRET}

  beam {
    host = changeme
    host = ${?BEAM_HOST}
    port = 80
    port = ${?BEAM_PORT}
    sslPort = 443
    sslPort = ${?BEAM_SSL_PORT}
  }
}
