package com.malliina.musicpimp.json

object JsonStrings {
  val Cmd = "cmd"
  val Ping = "ping"
  val PingAuth = "ping_auth"
  val Authenticate = "authenticate"
  val FolderKey = "folder"
  val RootFolder = "root_folder"
  val AlarmsKey = "alarms"
  val AlarmsEdit = "alarms_edit"
  val AlarmsAdd = "alarms_add"
  val SearchKey = "search"
  val Term = "term"
  val Limit = "limit"
  val Beam = "beam"
  val Id = "id"
  val TrackKey = "track"
  val RequestId = "request"
  val ServerKey = "s"
  val RegisteredKey = "registered"
  val UnregisterCmd = "unregister"
  val Event = "event"
  val UsernameKey = "username"
  val PasswordKey = "password"
  val Body = "body"
  val VersionKey = "version"
  val Reason = "reason"
  val StatusKey = "status"
  val Meta = "meta"
  val SuccessKey = "success"
  val PhonesKey = "phones"
  val ServersKey = "servers"
  val RequestsKey = "requests"
  val Address = "address"
  val Player = "player"
  val Start = "start"
  val EndExclusive = "end_exclusive"
  val Range = "range"

  val PlaylistsGet = "playlists"
  val PlaylistGet = "playlist"
  val PlaylistSave = "playlist_save"
  val PlaylistDelete = "playlist_delete"
  val PlaylistKey = "playlist"
  val PlaylistsKey = "playlists"

  val Recent = "recent"
  val Popular = "popular"

  val Cancel = "cancel"
}
