name: Package and release

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-26.04

    steps:
      - uses: actions/checkout@v7
      - name: Install lintian
        run: |
          sudo apt-get update
          sudo apt-get install -y lintian
      - uses: actions/setup-java@v6
        with:
          distribution: zulu
          java-version: 17
      - uses: sbt/setup-sbt@v1
      - name: Compile
        run: sbt "mode prod" Test/compile
      - name: Build deb packages
        run: |
          sbt "mode prod" musicpimp/Deb/packageBin pimpcloud/Deb/packageBin
      - name: Release .deb packages
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            **/*.deb
