name: Test

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
          cache: sbt
      - name: Compile
        run: sbt Test/compile
      - name: Build deb package
        run: |
          sudo apt-get install -y lintian
          sbt "set scalaJSStage in Global := FullOptStage" musicpimp/ciBuild musicmeta/ciBuild pimpcloud/ciBuild
