name: Package and release

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
          cache: sbt
      - name: Compile
        run: sbt Test/compile
      - name: Build deb packages
        run: |
          sudo apt-get install -y lintian
          sbt "set scalaJSStage in Global := FullOptStage" musicpimp/Debian/packageBin pimpcloud/Debian/packageBin
      - name: Release .deb packages
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            */*.deb
